name: 编译并打包 ARMHF 驱动为 Deb 包
on:
  push:
    branches: [ main ]  # 推送代码触发
  workflow_dispatch:     # 手动触发

jobs:
  build-deb:
    runs-on: ubuntu-20.04
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4

      - name: 安装编译和打包依赖
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt update
          # 编译依赖（armhf 工具链 + CUPS 库）
          sudo apt install -y \
            crossbuild-essential-armhf \
            libcups2-dev:armhf \
            libcupsimage2-dev:armhf \
            libxml2-dev:armhf \
            libgtk2.0-dev:armhf \
            libglade2-dev:armhf \
            automake autoconf libtool
          # Debian 打包依赖（核心工具）
          sudo apt install -y \
            debhelper dpkg-dev fakeroot

      - name: 生成 ARMHF 编译脚本
        run: |
          cat > allgen-armhf.sh << 'EOF'
          #!/bin/sh
          set -x  # 开启命令调试（日志更详细）
          _prefix=/usr
          _libdir=/usr/lib/arm-linux-gnueabihf
          # 配置各模块（指定 armhf 宿主）
          cd ppd && ./autogen.sh --prefix=${_prefix} --host=arm-linux-gnueabihf && cd ..
          cd pstoufr2cpca && ./autogen.sh --prefix=${_prefix} --host=arm-linux-gnueabihf && cd ..
          cd backend && ./autogen.sh --prefix=${_prefix} --host=arm-linux-gnueabihf && cd ..
          cd cngplp && ./autogen.sh --prefix=${_prefix} --libdir=${_libdir} --host=arm-linux-gnueabihf && cd ..
          cd cpca && ./autogen.sh --prefix=${_prefix} --enable-static --disable-shared --host=arm-linux-gnueabihf && cd ..
          EOF
          chmod +x allgen-armhf.sh

      - name: 执行编译（带调试日志）
        run: |
          ./allgen-armhf.sh
          make -j$(nproc)  # 多线程编译（若卡壳可改为 make）

      - name: 打包为 Deb 包（标准流程）
        run: |
          # 使用 debhelper 标准流程打包
          debuild -us -uc -a armhf  # -us/-uc: 不签名；-a: 指定架构
          # 将生成的 Deb 包移动到当前目录（debuild 会输出到上级目录）
          mv ../cndrvcups-lb-armhf_*.deb ./

      - name: 上传 Deb 包
        uses: actions/upload-artifact@v4
        with:
          name: canon-mf4452-armhf-deb
          path: cndrvcups-lb-armhf_*.deb  # 匹配所有版本的 Deb 包
